export const FETCHING_PRODUCT ='FETCHING_PRODUCT';
export const FETCHING_PRODUCT_SUCCESSFUL ='FETCHING_PRODUCT_SUCCESSFUL';
export const FETCHING_PRODUCT_FAILURE ='FETCHING_PRODUCT_FAILURE';
export const GET_RECENT_SEARCH ='GET_RECENT_SEARCH';